[theme]

# Primary accent for interactive elements
primaryColor = '#C998FF'

# Background color for the main content area
backgroundColor = '#0C0217'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#391F54'

# Color used for almost all text
textColor = '#F7EEFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
